let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Kurtas",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/kurtas/k1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Kurtas",
    price: 700,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/kurtas/k2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Kurtas",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/kurtas/k3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Kurtas",
    price: 700,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/kurtas/k4.jpg",
  },
  {
    id: "baoewpf",
    name: "Dresses",
    price: 550,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/dresses/d1.jpg",
  },
  {
    id: "nioeqfpn",
    name: "Dresses",
    price: 700,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/dresses/d2.jpg",
  },
  {
    id: "cpaweiub",
    name: "Dresses",
    price: 550,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/dresses/d3.jpg",
  },
  {
    id: "askjn",
    name: "Dresses",
    price: 700,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/dresses/d4.jpg",
  },

  // mens 
  {
    id: "askdenoe",
    name: "Jackets",
    price: 600,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/jackets/j1.jpg",
  },
  {
    id: "anwdopn",
    name: "Jackets",
    price: 850,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/jackets/j2.jpg",
  },
  {
    id: "ipbdeu",
    name: "Jackets",
    price: 600,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/jackets/j3.jpg",
  },
  {
    id: "askjnsabd",
    name: "Jackets",
    price: 850,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/jackets/j4.jpg",
  },
  {
    id: "askden",
    name: "Shirts",
    price: 900,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/shirts/s1.jpg",
  },
  {
    id: "anwdo",
    name: "Shirts",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/shirts/s2.jpg",
  },
  {
    id: "ipb",
    name: "Shirts",
    price: 800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/shirts/s3.jpg",
  },
  {
    id: "askjnsa",
    name: "Shirts",
    price: 600,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/img1/shirts/s4.jpg",
  },
];
